{"name": "test_step_creation", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('custom_user', <SubRequest 'setup_step_data' for <Function test_step_creation>>)", "trace": "file C:\\Users\\hemap\\Desktop\\cookflow-backend\\recipes\\tests\\test_model.py, line 295\n      def test_step_creation(self, setup_step_data):\nfile C:\\Users\\hemap\\Desktop\\cookflow-backend\\recipes\\tests\\test_model.py, line 288\n      @pytest.fixture\n      def setup_step_data(self, custom_user):\nE       fixture 'custom_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, client, db, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, faker, live_server, mailoutbox, monkeypatch, other_user_data, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_step_data, test_recipe, test_superuser, test_unit, test_unit_type, test_user, test_user_data, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\hemap\\Desktop\\cookflow-backend\\recipes\\tests\\test_model.py:288"}, "description": "Tests that a Step can be created successfully.", "start": 1749832720440, "stop": 1749832720440, "uuid": "53d2b2ef-9dad-4922-99bf-f3a9d1272035", "historyId": "d53e80f62dc6309db399c194800f2eb6", "testCaseId": "d53e80f62dc6309db399c194800f2eb6", "fullName": "recipes.tests.test_model.TestStepModel#test_step_creation", "labels": [{"name": "tag", "value": "recipes_app"}, {"name": "tag", "value": "models"}, {"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "recipes.tests"}, {"name": "suite", "value": "test_model"}, {"name": "subSuite", "value": "TestStepModel"}, {"name": "host", "value": "Pincho"}, {"name": "thread", "value": "13104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "recipes.tests.test_model"}]}